# Generated by Django 5.1.6 on 2025-07-29 11:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori')),
            ],
            options={
                'verbose_name': 'Mamlakat ',
                'verbose_name_plural': 'Mamlakatlar',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori')),
            ],
            options={
                'verbose_name': 'Janr ',
                'verbose_name_plural': 'Janrlar',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Sarlavhasi')),
                ('slug', models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('duration', models.CharField(default='1 soat 59 daqiqa 59 soniya', max_length=30, verbose_name='Davomiyligi')),
                ('language', models.CharField(default="O'zbek tilida", max_length=15, verbose_name='Tili')),
                ('year', models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili')),
                ('age_limit', models.CharField(choices=[('0+', '0+'), ('6+', '6+'), ('12+', '12+'), ('16+', '16+'), ('18+', '18+')], max_length=3, verbose_name='Yosh chegarasi')),
                ('like', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yoqtirishlar')),
                ('dislike', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yoqtirmasliklar')),
                ('view', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Ko'rishlar")),
                ('photo', models.ImageField(upload_to='movies/', verbose_name='Surati')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to='api.country', verbose_name='Mamlakati')),
                ('genre', models.ManyToManyField(related_name='movies', to='api.genre', verbose_name='Janri')),
            ],
            options={
                'verbose_name': 'Film ',
                'verbose_name_plural': 'Filmlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=7)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MovieURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Sarlavhasi')),
                ('type', models.CharField(choices=[('trailer', 'Treyler'), ('movie', 'Film'), ('series', 'Serial')], max_length=10, verbose_name='Turi')),
                ('part', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qismi')),
                ('embed_input', models.TextField(help_text='YouTube yoki Mover.uz\'dan quyidagi formatlarda <b>iframe</b> yoki <b>video URL</b> kiriting:<br><br><b>Masalan (Film yoki Serial uchun):</b><br><code>&lt;iframe src="https://www.youtube.com/embed/abc123"&gt;&lt;/iframe&gt;</code><br>yoki<br><code>https://mover.uz/video/embed/kb0pUqVX</code><br><br><b>Agar turi <i>Treyler</i> bo‘lsa:</b><br>Oddiy video URL havolasini kiriting, masalan:<br><code>https://youtu.be/1ovgxN2VWNc</code>', verbose_name='Saytdan joylashtiriladigan video URL')),
                ('embed_url', models.URLField(editable=False, verbose_name='Tozalangan URL')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_url', to='api.movie', verbose_name='FIlmi')),
            ],
            options={
                'verbose_name': 'Havola ',
                'verbose_name_plural': 'Havolalar',
                'ordering': ['movie', 'part'],
                'constraints': [models.UniqueConstraint(fields=('movie', 'part'), name='unique_movie_part')],
            },
        ),
    ]
