# Generated by Django 5.1.3 on 2025-03-04 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default=0, max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
