# Generated by Django 5.1.6 on 2025-07-29 06:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genres',
            options={'verbose_name': 'Janr ', 'verbose_name_plural': 'Janrlar'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'ordering': ['-created_at'], 'verbose_name': 'Film ', 'verbose_name_plural': 'Filmlar'},
        ),
        migrations.AlterModelOptions(
            name='movieurl',
            options={'verbose_name': 'Havola ', 'verbose_name_plural': 'Havolalar'},
        ),
        migrations.AddField(
            model_name='movieurl',
            name='type',
            field=models.CharField(choices=[('trailer', 'Treyler'), ('movie', 'Film'), ('series', 'Serial')], default=0, max_length=10, verbose_name='Turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='genres',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Qo'shilgan vaqti"),
        ),
        migrations.AlterField(
            model_name='movies',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='dislike',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yoqtirmasliklar'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(default='00:00:00', max_length=8, verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='api.genres', verbose_name='Janri'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(default="O'zbek tilida", max_length=15, verbose_name='Tili'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='like',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Yoqtirishlar'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='photo',
            field=models.ImageField(upload_to='movies/', verbose_name='Surati'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name='Identifikatori'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Sarlavhasi'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='view',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name="Ko'rishlar"),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.PositiveIntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='embed_input',
            field=models.TextField(help_text='YouTube yoki Mover.uz\'dan <b>iframe</b> yoki <b>src URL</b> kiriting.<br>Masalan: <br><code>&lt;iframe src="https://www.youtube.com/embed/abc123"&gt;&lt;/iframe&gt;</code><br>yoki <code>https://mover.uz/video/embed/kb0pUqVX</code>', verbose_name='Saytdan joylashtiriladigan video URL'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_url', to='api.movies', verbose_name='FIlmi'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='part',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Qismi'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Sarlavhasi'),
        ),
    ]
