# Generated by Django 5.1.6 on 2025-07-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(choices=[("O'zbek tilida", "O'zbek tilida"), ('Ingliz tilida', 'Ingliz tilida'), ('Rus tilida', 'Rus tilida')], max_length=15, verbose_name='Tili'),
        ),
    ]
