# Generated by Django 5.1.6 on 2025-07-29 06:36

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_genres_options_alter_movies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0), verbose_name='Davomiyligi'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='year',
            field=models.PositiveIntegerField(default=2025, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)], verbose_name='Yili'),
        ),
    ]
