# Generated by Django 5.1.3 on 2025-03-04 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_movies_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='language',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
