# Generated by Django 5.1.6 on 2025-07-29 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_movies_duration_alter_movies_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='duration',
            field=models.CharField(default='1 soat 59 daqiqa 59 soniya', max_length=30, verbose_name='Davomiyligi'),
        ),
    ]
