# Generated by Django 5.1.6 on 2025-03-05 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movies_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='language',
            field=models.CharField(default="O'zbek tilida", max_length=15),
        ),
        migrations.CreateModel(
            name='MovieReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(max_length=7)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movies')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
