# Generated by Django 5.1.6 on 2025-07-29 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_movies_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieurl',
            options={'ordering': ['part'], 'verbose_name': 'Havola ', 'verbose_name_plural': 'Havolalar'},
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='embed_input',
            field=models.TextField(help_text='YouTube yoki Mover.uz\'dan quyidagi formatlarda <b>iframe</b> yoki <b>video URL</b> kiriting:<br><br><b>Masalan (Film yoki Serial uchun):</b><br><code>&lt;iframe src="https://www.youtube.com/embed/abc123"&gt;&lt;/iframe&gt;</code><br>yoki<br><code>https://mover.uz/video/embed/kb0pUqVX</code><br><br><b>Agar turi <i>Treyler</i> bo‘lsa:</b><br>Oddiy video URL havolasini kiriting, masalan:<br><code>https://youtu.be/1ovgxN2VWNc</code>', verbose_name='Saytdan joylashtiriladigan video URL'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='embed_url',
            field=models.URLField(editable=False, verbose_name='Tozalangan URL'),
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='part',
            field=models.PositiveIntegerField(unique=True, verbose_name='Qismi'),
        ),
    ]
