# Generated by Django 5.1.6 on 2025-07-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_movieurl_options_alter_movieurl_embed_input_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movieurl',
            options={'ordering': ['movie', 'part'], 'verbose_name': 'Havola ', 'verbose_name_plural': 'Havolalar'},
        ),
        migrations.AlterField(
            model_name='movieurl',
            name='part',
            field=models.PositiveIntegerField(default=0, verbose_name='Qismi'),
        ),
        migrations.AddConstraint(
            model_name='movieurl',
            constraint=models.UniqueConstraint(fields=('movie', 'part'), name='unique_movie_part'),
        ),
    ]
