# Generated by Django 5.1.6 on 2025-07-29 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_movieurl_options_alter_movieurl_part_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieurl',
            name='part',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Qismi'),
        ),
    ]
