# Generated by Django 5.1.6 on 2025-08-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='title',
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(default=0, max_length=150, verbose_name='Mavzusi'),
            preserve_default=False,
        ),
    ]
